CREATE TABLE favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    imdb_id TEXT NOT NULL,
    
    user_id TEXT NOT NULL,
    
    title TEXT NOT NULL,
    year TEXT,
    poster TEXT,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT unique_user_movie UNIQUE(user_id, imdb_id)
);